####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  testing-postgres-data:
    driver: local

  # MySQL Data
  diegofelix-mysql-data:
    driver: local

  # Redis Data
  testing-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: diegofelix-mysql
    volumes:
      - diegofelix-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=diegofelix
      - MYSQL_DATABASE=diegofelix
      - MYSQL_USER=diegofelix
      - MYSQL_PASSWORD=diegofelix

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: testing-redis
    command: --appendonly yes
    volumes:
      - testing-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-nginx
    container_name: testing-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0-nginx
    container_name: testing-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
