####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  battleroad-mysql-data:
    driver: local

  # Redis Data
  battleroad-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: battleroad-mysql
    volumes:
      - battleroad-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=battleroad
      - MYSQL_DATABASE=battleroad
      - MYSQL_USER=battleroad
      - MYSQL_PASSWORD=battleroad

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: battleroad-redis
    command: --appendonly yes
    volumes:
      - battleroad-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-nginx
    container_name: battleroad-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0-nginx
    container_name: battleroad-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
